BusinessCard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('CardApp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CardApp/urls.py
from django.urls import path
from .views import navListView, MyJobView, EmailAttachementView, SubscribeFormViews

app_name = 'CardApp'

urlpatterns = [
    path('', navListView.as_view(), name='home'),
    path('job/<slug:slug>/', MyJobView.as_view(), name='MyJobView'),
    path('send', EmailAttachementView.as_view(), name='emailattachment'),
    path('subs/', SubscribeFormViews, name ='subs')
]

CardApp/models.py
from django.db import models
from pytils import translit
from django.utils.datetime_safe import date
from django.urls import reverse
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
# from django.utils.translation import ugettext_lazy as _

# Create your models here.


class logo(models.Model):
    logotype = models.TextField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return 'Ваше лого'


class nav(models.Model):
    nav = models.CharField(
        verbose_name='Изменить текст пункта меню',
        max_length=150,
        blank=True,
        null=True,
    )
    SlugNav = models.CharField(
        verbose_name='Ссылка или якорь пункта меню',
        max_length=400,
        unique=True,
    )

    def __str__(self):
        return self.nav


class hero(models.Model):
    TopFirstH1 = models.CharField(
        verbose_name='Изменить текст первого H1',
        max_length=150,
        blank=True,
        null=True,
    )
    TopFirstH2 = models.CharField(
        verbose_name='Изменить текст первого H2',
        default='Ваш текст',
        max_length=150,
        blank=True,
        null=True,
    )
    GetStartedBtn = models.CharField(
        verbose_name='Изменить текст первой кнопки',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockTitle1 = models.CharField(
        verbose_name='Изменить название первого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText1 = models.TextField(
        verbose_name='Изменить текст первого карт блока',
        blank=True,
        null=True,
    )
    TopCardBlockTitle2 = models.CharField(
        verbose_name='Изменить название второго карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText2 = models.TextField(
        verbose_name='Изменить текст второго карт блока',
        blank=True,
        null=True,
    )
    TopCardBlockTitle3 = models.CharField(
        verbose_name='Изменить название третьего карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText3 = models.TextField(
        verbose_name='Изменить текст третьего карт блока',
        blank=True,
        null=True,
    )
    TopCardBlockTitle4 = models.CharField(
        verbose_name='Изменить название четвертого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText4 = models.TextField(
        verbose_name='Изменить текст четвертого карт блока',
        blank=True,
        null=True,
    )
    TopFirstH1 = models.CharField(
        verbose_name='Изменить текст первого H1',
        max_length=150,
        blank=True,
        null=True,
    )
    TopFirstH2 = models.CharField(
        verbose_name='Изменить текст первого H2',
        default='Ваш текст',
        max_length=150,
        blank=True,
        null=True,
    )
    GetStartedBtn = models.CharField(
        verbose_name='Изменить текст первой кнопки',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockTitle1 = models.CharField(
        verbose_name='Изменить название первого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText1 = models.TextField(
        verbose_name='Изменить текст первого карт блока',
        blank=True,
        null=True,
    )
    TopCardBlockTitle2 = models.CharField(
        verbose_name='Изменить название второго карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText2 = models.TextField(
        verbose_name='Изменить текст второго карт блока',
        blank=True,
        null=True,
    )
    TopCardBlockTitle3 = models.CharField(
        verbose_name='Изменить название третьего карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText3 = models.TextField(
        verbose_name='Изменить текст третьего карт блока',
        blank=True,
        null=True,
    )
    TopCardBlockTitle4 = models.CharField(
        verbose_name='Изменить название четвертого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    TopCardBlockText4 = models.TextField(
        verbose_name='Изменить текст четвертого карт блока',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.TopFirstH1


class AboutSection(models.Model):
    AboutSectionP = models.TextField(
        verbose_name='Изменить текст под тегом h2 во второй секции',
        blank=True,
        null=True,
    )
    AboutButton = models.CharField(
        verbose_name='Изменить текст кнопки второго сектора',
        max_length=150,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.AboutButton


class CountsSection(models.Model):
    CounterNumber1 = models.IntegerField(
        verbose_name='Изменить цифры счетчика второго сектора 1',
        blank=True,
        null=True,
    )
    CounterTitle1 = models.CharField(
        verbose_name='Изменить текст под счетчиком второго сектора 1',
        max_length=150,
        blank=True,
        null=True,
    )
    CounterNumber2 = models.IntegerField(
        verbose_name='Изменить цифры счетчика второго сектора 2',
        blank=True,
        null=True,
    )
    CounterTitle2 = models.CharField(
        verbose_name='Изменить текст под счетчиком второго сектора 2',
        max_length=150,
        blank=True,
        null=True,
    )
    CounterNumber3 = models.IntegerField(
        verbose_name='Изменить цифры счетчика второго сектора 3',
        blank=True,
        null=True,
    )
    CounterTitle3 = models.CharField(
        verbose_name='Изменить текст под счетчиком второго сектора 3',
        max_length=150,
        blank=True,
        null=True,
    )
    CounterNumber4 = models.IntegerField(
        verbose_name='Изменить цифры счетчика второго сектора 4',
        blank=True,
        null=True,
    )
    CounterTitle4 = models.CharField(
        verbose_name='Изменить текст под счетчиком второго сектора 4',
        max_length=150,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.CounterTitle1


class AboutVideoSection(models.Model):
    AboutVideoSectionPlug = models.ImageField(
        verbose_name='Картинка для заглушки видео',
        help_text='Рекомендованное разрешение для заглушки: 1024 х 760',
        upload_to='AboutVideoSection'
    )
    AboutVideoSectionUrl = models.CharField(
        verbose_name='Ссылка на видео',
        max_length=150,
        blank=True,
        null=True,
    )
    # AboutVideoSectionH3 = models.CharField(
    #     verbose_name='Изменить заголовок',
    #     max_length=150,
    #     blank=True,
    #     null=True,
    # )
    AboutVideoSectionP = models.TextField(
        verbose_name='Текст под заговолком',
        blank=True,
        null=True
    )
    

    def __str__(self):
        return 'обьект {}'.format(self.pk,)


class reviews(models.Model):
    TextReviews = models.TextField(
        verbose_name='Текст отзыва',
        blank=True,
        null=True,
    )
    PhotoReviews = models.ImageField(
        verbose_name='Фото клиента',
        help_text='Рекомендованное разрешение для фото: 400 х 400',
        upload_to='reviews'
    )
    FioReviews = models.CharField(
        verbose_name='Имя фамилия клиента',
        max_length=250,
        blank=True,
        null=True,
    )
    RoleReviews = models.CharField(
        verbose_name='роль клиента',
        max_length=250,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.FioReviews


class TestimonialsAndSevicesText(models.Model):
    TestimonialsH3 = models.CharField(
        verbose_name='Изменить заголовок секции Testimonials',
        max_length=150,
        blank=True,
        null=True,
    )
    TestimonialsP = models.TextField(
        verbose_name='Изменить текст под заговолком Testimonials',
        blank=True,
        null=True,
    )
    SevicesH3 = models.CharField(
        verbose_name='Изменить заголовок секции Sevices',
        max_length=150,
        blank=True,
        null=True,
    )
    SevicesP = models.TextField(
        verbose_name='Изменить текст под заговолком Sevices',
        blank=True,
        null=True,
    )
    SevicesCardBlockTitle1 = models.CharField(
        verbose_name='Изменить название первого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    SevicesCardBlockText1 = models.TextField(
        verbose_name='Изменить текст первого карт блока',
        blank=True,
        null=True,
    )
    SevicesCardBlockTitle2 = models.CharField(
        verbose_name='Изменить название второго карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    SevicesCardBlockText2 = models.TextField(
        verbose_name='Изменить текст второго карт блока',
        blank=True,
        null=True,
    )
    SevicesCardBlockTitle3 = models.CharField(
        verbose_name='Изменить название третьего карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    SevicesCardBlockText3 = models.TextField(
        verbose_name='Изменить текст третьего карт блока',
        blank=True,
        null=True,
    )
    SevicesCardBlockTitle4 = models.CharField(
        verbose_name='Изменить название четвертого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    SevicesCardBlockText4 = models.TextField(
        verbose_name='Изменить текст четвертого карт блока',
        blank=True,
        null=True,
    )
    SevicesCardBlockTitle5 = models.CharField(
        verbose_name='Изменить название пятого карт блока',
        max_length=150,
        blank=True,
        null=True,
    )
    SevicesCardBlockText5 = models.TextField(

CardApp/forms.py
from django import forms


class EmailForm(forms.Form):
    name = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Имя'}))
    email = forms.EmailField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Почта'}))
    subject = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Тема'}))
    attach = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'сообщение'}),)

class SubscribeForm(forms.Form):
    """
    docstring
    """
    SubEemail = forms.EmailField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=True)

CardApp/views.py
from django.http import HttpResponseRedirect
from django.http import JsonResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from django.core.mail import EmailMessage, send_mail
from BusinessCard.settings import RECIPIENTS_EMAIL, DEFAULT_FROM_EMAIL
from .forms import EmailForm, SubscribeForm
from .models import *
# Create your views here.


class navListView(ListView):
    method_decorator(csrf_exempt)
    model = nav
    template_name = "CardApp/index.html"
    context_object_name = 'nav'
    # form_class = SubscribeForm

    def get_context_data(self, **kwargs):
        context = super(navListView, self).get_context_data(**kwargs)
        context['logo'] = logo.objects.all()
        context['hero'] = hero.objects.all()
        context['reviews'] = reviews.objects.all()
        context['AboutSection'] = AboutSection.objects.all()
        context['CountsSection'] = CountsSection.objects.all()
        context['AboutVideoSection'] = AboutVideoSection.objects.all()
        context['TestimonialsAndSevicesText'] = TestimonialsAndSevicesText.objects.all()
        context['CtaSection'] = CtaSection.objects.all()
        context['pricing'] = pricing.objects.all()
        context['team'] = team.objects.all()
        context['QuestionsSectionText'] = QuestionsSectionText.objects.all()
        context['GenericAsk'] = GenericAsk.objects.all()
        context['TeamText'] = TeamText.objects.all()
        context['JobText'] = JobText.objects.all()
        context['Jobcategory'] = Jobcategory.objects.all()
        context['MyJob'] = MyJob.objects.all()
        context['contact'] = contact.objects.all()
        context['FooterListHeaders'] = FooterListHeaders.objects.all()
        context['FooterLinksTwo'] = FooterLinksTwo.objects.all()
        context['FooterSubscribeF'] = FooterSubscribeF.objects.all()
        context['SocNet'] = SocNet.objects.all()
        context['EmailForm'] = EmailForm()
        context['SubscribeForm'] = SubscribeForm()
        return context


class EmailAttachementView(View):
    method_decorator(csrf_exempt)
    form_class = EmailForm
    template_name = 'CardApp/email_form.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'email_form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():

            subject = form.cleaned_data['subject'].strip()
            message = "{name} / {email} said: ".format(
                name=form.cleaned_data.get('name'),
                email=form.cleaned_data.get('email'))
            message += "\n\n{0}".format(form.cleaned_data.get('message'))
            email = form.cleaned_data['email']
            files = request.FILES.getlist('attach')

            try:
                mail = EmailMessage(
                    subject=subject, body=message, from_email=email, to=RECIPIENTS_EMAIL)
                for f in files:
                    mail.attach(f.name, f.read(), f.content_type)
                mail.send()
                return render(request, self.template_name, {'email_form': form, 'error_message': 'письмо отправлено на %s' % email})
            except:
                return render(request, self.template_name, {'email_form': form, 'error_message': 'Файл слишком велик'})

            return render(request, self.template_name, {'email_form': form, 'error_message': 'возникла ошибка, попробуйте позже'})


def SubscribeFormViews(request):
    SUBJECT = "The message from a contact form"
    message = '''try'''
    if not request.is_ajax():
        raise Http404('No ajax!')
    else:
        form = SubscribeForm(request.POST or None)
        if form.is_valid():
            EMAIL_TO = form.cleaned_data['SubEemail']
            send_mail(SUBJECT, message, DEFAULT_FROM_EMAIL, [EMAIL_TO])
            # print(email_content)
            r = {'form_is_valid': True}
        else:
            r = {'form_is_valid': False, 'form_errors': form.errors.as_json()}
    return JsonResponse(r)

class MyJobView(DetailView):
    method_decorator(csrf_exempt)
    
    model = MyJob
    template_name = 'CardApp/portfolio-details.html'

    def get_context_data(self, **kwargs):
        context = super(MyJobView, self).get_context_data(**kwargs)
        context['logo'] = logo.objects.all()
        context['Jobcategory'] = Jobcategory.objects.all()
        context['nav'] = nav.objects.all()
        context['contact'] = contact.objects.all()
        context['SocNet'] = SocNet.objects.all()
        context['FooterListHeaders'] = FooterListHeaders.objects.all()
        context['FooterLinksTwo'] = FooterLinksTwo.objects.all()
        context['FooterSubscribeF'] = FooterSubscribeF.objects.all()
        context['SubscribeForm'] = SubscribeForm()
        return context

templates/CardApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="csrf-param" content="_csrf">
    <meta name="csrf-token" content="aKvoKaATAmSuJOKntluVitE4z7iVTUnqor1RTyZNkhcLOGZTkPCBH1UbFN9W5fSW">

    <title>OnePage Bootstrap Template - Index</title>
    <meta content="" name="descriptison" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon" />
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet" />

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <!-- =======================================================
  * Template Name: OnePage - v2.1.0
  * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/======================================================== -->
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">
            {{logo.0.logotype|safe}}
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo mr-auto"><img src="{% static '/img/logo.png" alt' %}="" class="img-fluid"></a>-->

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    {% for text in nav %}
                    <li class="{% if forloop.counter == 1 %} active {% endif %}">
                        <a href="{{text.SlugNav}}">{{text.nav}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </nav>
            <!-- .nav-menu -->
        </div>
    </header>
    <!-- End Header -->

    {% block content %} {% endblock content %}

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>{{logo.0.logotype|safe}}</h3>
                        <p>{{contact.0.location}} <br />
                            <strong>{{contact.0.EmailTitle}}:</strong> {{contact.0.Email}}<br />
                            <strong>{{contact.0.CallTitle}}:</strong> {{contact.0.call}}<br />
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>{{FooterListHeaders.0.FooterRtitle1}}</h4>
                        <ul>
                            {% for text in nav %}
                            <li class="bx bx-chevron-right">
                                <a href="{{text.SlugNav}}">{{text.nav}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>{{FooterListHeaders.0.FooterRtitle2}}</h4>
                        <ul>
                            {% for i in FooterLinksTwo %}
                            <li>
                                <i class="bx bx-chevron-right"></i> <a href="{{i.SlugFooter}}">{{i.FooterLink}}</a>
                            </li>
                            {% endfor %}
                            
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>{{FooterSubscribeF.0.FooterSubh4}}</h4>
                        <p>{{FooterSubscribeF.0.FooterSubP}}</p>
                        <form action="" method="post" id="FormSub">
                            {% csrf_token %}
                            {{SubscribeForm.SubEemail}}
                            <div class="validate"></div>
                            <input type="submit" value="Подписаться" id="AjaxSend">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">
            <div class="mr-md-auto text-center text-md-left">
                <div class="copyright">
                    &copy; Copyright <strong><span>OnePage</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/onepage-mu/ltipurpose-bootstrap-template/ -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                {% for soc in SocNet %}
                <a href="{{soc.SocUrl}}" class="{{soc.SocIcon}}"><i class="bx bxl-{{soc.SocIcon}}"></i></a>
                {% endfor %}
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static '/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static '/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static '/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static '/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static '/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static '/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static '/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static '/js/main.js' %}"></script>
    <!-- <script src="{% static '/js/SendMailAjax.js' %}"></script> -->

    <!-- Other JS -->
    <script>
    </script>
    <script>
        emailExp = /^[^\s()<>@,;:\/]+@\w[\w\.-]+\.[a-z]{2,}$/i;

        $(document).ready(function () {
            console.log('test');
            $('#AjaxSend').on('click', function (e) {
                e.preventDefault();
                var SubEemail = $('#id_SubEemail').val();
                if(SubEemail.indexOf("@") < 0 || SubEemail.indexOf(".") < 0) {
                    alert('Неправильный формат почты');
                    return;
                } else {
                    console.log();
                }
                var test = $('#FormSub input:hidden').val();
                var data = {
                    SubEemail: SubEemail,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                };


                $.ajax({
                    type: "post",
                    url: "http://127.0.0.1:8000/subs/",
                    data: data,
                    success: function (response) {
                        console.log(response);
                        alert('Вы подписались, спасибо!')
                    },
                    error: function (error) {
                        console.log(JSON.stringify(error));
                        console.log(data);
                    }
                });
            })
        });
        // const csrftoken = Cookies.get('csrftoken');
    </script>
</body>

</html>

templates/CardApp/email_form.html
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/timer.css' %}">

{% block content %}


<br>
<br>
<br>
<div class="col-lg-8 mt-15 mt-lg-10">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="mt-5 mb-3">Письмо отправленно</h1>
                <h2>Возвращение на главную через:</h2>
                <div class="timer">
                    <div class="timer_line"></div>
                    <div class="timer_body">
                        <div class="timer_counter">
                            <span></span>
                            <span>5</span>
                            <span>4</span>
                            <span>3</span>
                            <span>2</span>
                            <span>1</span>
                        </div>
                    </div>
                </div>
                {% if email_form.error_message %}
                <div class="alert alert-primary" role="alert">
                    {{email_form.error_message}}
                </div>
                {% endif %}


                <form method="POST" action="http://127.0.0.1:8000/send" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{email_form|crispy}}
                    <button type="submit" class="btn btn-primary">Send Email</button>
                </form>
            </div>

        </div>
    </div>
</div>

<script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        let TimeToRedirect = 5;
        setTimeout(function () {
            window.location = "/";
        }, 5000);
        $('form').hide();
    });
</script>
{% endblock content %}

templates/CardApp/portfolio-details.html
{% extends 'CardApp/base.html' %}

{% block content %}
<main id="main">

  <!-- ======= Breadcrumbs ======= -->


  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>{{object.MyJobProductTitle}}</h2>
        <ol>
          <li><a href="index.html">{{object.TopLiNav1}}</a></li>
          <li>Portfolio Details</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container" data-aos="fade-up">


      <div class="portfolio-details-container">
        <div class="owl-carousel portfolio-details-carousel">

          <img src="{{object.MyJobImage1.url}}" class="img-fluid" alt="">
          <img src="{{object.MyJobImage2.url}}" class="img-fluid" alt="">
          <img src="{{object.MyJobImage3.url}}" class="img-fluid" alt="">
        </div>
        <div class="portfolio-info">
          <h3>{{object.MyJobProductTitle}}</h3>
          <ul>
            <li><strong>{{object.MyJobJobCategoryTitle}}</strong>: {{object.MyJobJobCategory}}</li>
            <li><strong>{{object.MyJobClientTitle}}</strong>: {{object.MyJobClient}}</li>
            <li><strong>{{object.MyJobDateTitle}}</strong>: {{object.MyJobDate}}</li>
            
            {% if object.CheckLink == True %}
            <li><strong>{{object.MyJobUrlTitle}}</strong>: <a
                href="{{object.ExternalLink}}">{{object.ExternalLink}}</a></li>
            {% else %}
            <li><strong>{{object.MyJobUrlTitle}}</strong>: <a
                href="{{object.get_absolute_url}}">{{object.get_absolute_url}}</a></li>
              
            {% endif %}
              
          </ul>
        </div>

      </div>

      <div class="portfolio-description">
        <h2>{{object.MyJobH2}}</h2>
        <p>{{object.MyJobDescription}}</p>
      </div>
    </div>
  </section><!-- End Portfolio Details Section -->

</main><!-- End #main -->
{% endblock content %}